eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.oauth2: TRACE

server:
  port: 8082

spring:
  application:
    name: pets-microservice

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTHORIZATION_SERVER_URI:http://localhost:9000}


  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost:5432}/floofl-db
    username: devandre
    password: password