eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8081

spring:
  application:
    name: pets-microservice

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost:5432}/floofl-db
    username: devandre
    password: password