eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

server:
  error:
    include-exception: true

spring:
  mvc:
    problemdetails:
      enabled: true
  datasource:
    username: devandre
    password: password
    url: jdbc:postgresql://localhost:5432/floofl-db
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect